networks:
  supabase_network:
    driver: bridge

volumes:
  db_data:
  supabase_functions:

services:
  db:
    container_name: supabase-db
    image: supabase/postgres:15.1.1.78
    networks:
      - supabase_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    command: postgres -c config_file=/etc/postgresql/postgresql.conf -c log_min_messages=fatal
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  meta:
    container_name: supabase-meta
    image: supabase/postgres-meta:v0.80.0
    depends_on:
      db:
        condition: service_healthy
    networks:
      - supabase_network
    restart: always
    environment:
      PG_META_PORT: 8080
      PG_META_DB_HOST: db
      PG_META_DB_PASSWORD: ${POSTGRES_PASSWORD}

  auth:
    container_name: supabase-auth
    image: supabase/gotrue:v2.132.3
    depends_on:
      db:
        condition: service_healthy
    networks:
      - supabase_network
    restart: always
    environment:
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/postgres?sslmode=disable
      GOTRUE_SITE_URL: ${SITE_URL}
      GOTRUE_JWT_SECRET: ${JWT_SECRET}
      GOTRUE_EXTERNAL_EMAIL_ENABLED: "false"

  rest:
    container_name: supabase-rest
    image: postgrest/postgrest:v11.2.2
    depends_on:
      db:
        condition: service_healthy
    networks:
      - supabase_network
    restart: always
    ports:
      - "8000:3000"
    environment:
      PGRST_DB_URI: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/postgres
      PGRST_JWT_SECRET: ${JWT_SECRET}
      PGRST_DB_SCHEMAS: public,storage,graphql_public

  realtime:
    container_name: supabase-realtime
    image: supabase/realtime:v2.25.54
    depends_on:
      db:
        condition: service_healthy
    networks:
      - supabase_network
    restart: always
    environment:
      DB_HOST: db
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      PORT: 4000

  studio:
    container_name: supabase-studio
    image: supabase/studio:latest
    depends_on:
      - rest
      - auth
      - meta
    networks:
      - supabase_network
    restart: always
    ports:
      - "8082:3000"
    volumes:
      - supabase_functions:/tmp/supabase-edge-functions
    environment:
      STUDIO_PG_META_URL: http://meta:8080
      SUPABASE_URL: http://rest:3000
      SUPABASE_ANON_KEY: ${ANON_KEY}
      SUPABASE_SERVICE_ROLE_KEY: ${SERVICE_ROLE_KEY}
      SUPABASE_PUBLIC_URL: ${SUPABASE_PUBLIC_URL}
      EDGE_FUNCTIONS_MANAGEMENT_FOLDER: /tmp/supabase-edge-functions